PT-13027 - fix code-style and phpstan issues
shopware5/SwagBackendOrder pull request #30
Opened 2023-06-13 14:57 UTC by ennasus4sun

2023-06-14 09:16 UTC, mitelg requested changes
plugin.xml entry was also missing for the contribution

2023-06-14 12:19 UTC, mitelg requested changes

2023-06-14 12:19 UTC, mitelg commented on plugin.xml
> +            PT-13027 - Hinzufügen der Variable sTaxRates zur sOrder-Mail;
```suggestion
            PT-13027 - Die Steuern sind nun im Template der Bestellbestätigungsmail verfügbar;
```

please make sure, that this is not to technical, as this is for the shop owners/ merchants

2023-06-14 12:19 UTC, mitelg commented on plugin.xml
> +            PT-13027 - Add sTaxRates-variable to sOrder mail;
```suggestion
            PT-13027 - Taxes are now available in the order confirmation email template;
```

2023-06-14 12:19 UTC, mitelg commented on plugin.xml
> +    <version>3.0.3</version>
```suggestion
    <version>3.1.0</version>
```

changelog sounds like a feature to me :slightly_smiling_face:

2023-06-14 12:19 UTC, mitelg commented on plugin.xml
> +    <changelog version="3.0.3">
```suggestion
    <changelog version="3.1.0">
```

2023-06-15 07:35 UTC, swDennis approved these changes

2023-06-15 07:36 UTC, merged