feat(PT-12385): Country and state are now also displayed in the addre…
shopware5/SwagBackendOrder pull request #38
Opened 2023-07-13 11:17 UTC by swDennis

…ss selection

2023-07-13 12:32 UTC, mitelg requested changes

2023-07-13 12:33 UTC, mitelg commented on Tests/Functional/Controller/SwagBackendOrderTest.php
> +            static::assertArrayHasKey('countryName', $address);
shouldn't we test on the specific country and state? like in the asserts above?

2023-07-14 06:38 UTC, mitelg approved these changes

2023-07-14 12:13 UTC, rathmerdominik approved these changes

2023-07-14 12:13 UTC, merged